### PR TITLE
Remove .gitkeep files in lib directory

### PR DESCRIPTION
**Pull request by pizzaops**
The benefit of prepopulating the lib directories is outweighed by
the annoyance of accidentally pluginsyncing needless `.gitkeep` files to
all your nodes unless you remember to remove them.

`pluginsync` is already sufficiently opinionated about where things go.

### CODE REVIEW

**Comment by garethr** [comment]
Mmm, this will clober the lib folder which no-longer has anything in it though. I'd probably rather note this and add some starting point files for writing your own types and providers I think.

**Comment by pizzaops** [comment]
> Mmm, this will clober the lib folder which no-longer has anything in it though. I'd probably rather note this and add some starting point files for writing your own types and providers I think.

I realize that, but so what?

**Comment by walkamongus** [comment]
FWIW I think I agree with @pizzaops -- if someone wants to start building their own types and providers, I would hope they would know (or can easily figure out) they have to create the lib directories.

**Comment by rauchrob** [comment]
There is another approach, though: strip the `.gitkeep` files in `install.sh` (see my PR #92). That way the generated modules will have an empty `lib` directory etc.

**Comment by garethr** [comment]
Thanks for the discussion. I've merged #92 as an alternative solution to this issue. Cheers.

**Pull request closed without merging**
