### PR TITLE
Use rspec-puppet-facts

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by garethr** [comment]
@mcanevet ah, thanks for this. I'd been meaning to look into this. 

I noticed that currently this causes the specs on Travis to fail: https://travis-ci.org/garethr/puppet-module-skeleton/builds/51349763.

Would you be able to look at why that is? Thanks.

**Comment by mcanevet** [comment]
@garethr well, `rspec-puppet-facts` needs an `operatingsystem_support` section in metadata.json unless I specify which os to test with for example:

```puppet
on_supported_os({
    :hardwaremodels => ['i386', 'x86_64'],
    :supported_os   => [
      {
        "operatingsystem" => "Debian",
        "operatingsystemrelease" => [
          "6",
          "7"
        ]
      },
      {
        "operatingsystem" => "RedHat",
        "operatingsystemrelease" => [
          "5",
          "6"
        ]
      }
    ],
  }).each do |os, facts|
```

I'm not sure how to fix this cleanly in the scope of a skeleton

**Comment by garethr** [comment]
@mcanevet ah, then lets add a good default supported operating system array to the default metadata. This skeleton is advertised as being pretty opinionated, and it's a good way of encouraging people to use that metadata, which will make @ryanycoleman happy.

**Comment by mcanevet** [comment]
@garethr PR ammended with debian6,7 and redhat5,6,7. Is it OK like that?

**Comment by garethr** [comment]
@mcanevet And passing specs. Thanks. I think over time the general community can settle on a sensible default, but that works for me for now. Cheers

**Comment by ryanycoleman** [comment]
\o/

**Pull request merged**
