### PR TITLE
Improve strings compatibility

### PR DESCRIPTION
**Pull request by iankronquist**
This PR improves the compatibility of generated modules with the new puppet strings documentation
parser.
The .yardopts file tells yard, a code parsing library used by puppet strings, to parse documentation comments as markdown.
Yard has also been added to the Gemfile.
This PR addresses [PDOC 16](https://tickets.puppetlabs.com/browse/PDOC-16).

### CODE REVIEW

**Comment by hkenney** [comment]
@iankronquist Let's go ahead and squash these commits as well.

@garethr How do you feel about these changes? We're updating the `puppet module generate` skeleton so that it works with the puppet strings module out of the box and we felt we should do the same for this skeleton generator since it's so widely used.

**Comment by hkenney** [comment]
Let's also remove YARD from the Gemfile as we decided to do in the puppet version

**Comment by hkenney** [comment]
Looks like you brought some extra commits along with you? Maybe this needs a rebase?

**Comment by iankronquist** [comment]
rebased. Oops.

**Comment by garethr** [comment]
Looks good, thanks.

**Comment by iankronquist** [comment]
@garethr  thank you!

**Pull request merged**
