### PR TITLE
Use future parser for syntax test

### PR DESCRIPTION
**Pull request by aquister**

### CODE REVIEW

**Comment by garethr** [comment]
Hi @aquister. I'm going to close this as it prevents overriding this value using the ENV variable. You can see this in action here (ignore the rest of that file, it needs a good update) https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/.travis.yml#L20.

**Comment by aquister** [comment]
Would this be acceptable?

`PuppetSyntax.future_parser = true unless ENV['FUTURE_PARSER'] == 'no'`

**Comment by robinbowes** [comment]
What's the problem you're trying to solve here, @aquister ?

**Comment by aquister** [comment]
@robinbowes I just think the future parser should be default for new modules generated.

**Comment by robinbowes** [comment]
But that's actually fairly meaningless.

All your change does it to always use future parser for the syntax test, something that is done in the full test coverage by setting ```FUTURE_PARSER=yes```, as @garethr pointed out.

**Comment by aquister** [comment]
@robinbowes Only during travis build

**Comment by walkamongus** [comment]
Doesn't Puppet >= 4.0.0 not support future parser so this would break by default for those versions?

**Comment by garethr** [comment]
@aquister the future parser option only exists for Puppet 3.7 and 3.8, and for neither of them is it the default, so I'm inclined to keep it to the default. The feature flag (exposed in the tests via the ENV variable) is mainly a mechanism used to test out new code on the road to Puppet 4.

This project is intended as a skeleton, I'd envisage lots of orgs carry a fork with local opinions (not everyone will use Travis for instance). If you're running 3.8 with future parser in production, without an upcoming Puppet 4 upgrade in sight, then I'd definitely apply this locally. But for the community skeleton it's not a good default in my view.

**Pull request closed without merging**
