### PR TITLE
added listen gem to Gemfile for Ruby < 2.2

### LINKED ISSUE #124: Issue with listen gem version on Ruby 2.1.x
One of my co-workers ran into this today, using the latest version of the skeleton and I can duplicate it. When I run "bundle" with the included Gemfile on Ruby 2.1.7 I get:

> Installing listen 3.1.4
> 
> Gem::InstallError: listen requires Ruby version >= 2.2.3, ~> 2.2.

Guard is pulling in listen as a dependency:

listen <= 4.0, >= 2.7

listen is at 3.1.4 but that's not compatible with Ruby 2.1.x. It looks like that changed with listen version 3.1.0.

I'm still kind of a Ruby noob and I'm not sure what the best way to handle this is. If I add listen to my Gemfile it works:

gem "listen", "~> 3.0.0"

Do we want to add that to the Gemfile? Or should users just use 2.2.x? I usually try to stick to the same Ruby that Puppet uses which is 2.1.x for me.

I can fix my module's Gemfile but it seems like other people will run into this.

### PR DESCRIPTION
**Pull request by richburroughs**
Fixes #124.

Not sure if this is the route you want to go.

### CODE REVIEW

**Comment by cwood** [comment]
Iv had this same issue. I have also gotten new issues where we dont check in the gemfile.lock we now cant run rake

**Comment by richburroughs** [comment]
You could work around the issue in this PR by making that same change to your Gemfile.

I think I've seen the other thing you mentioned where rake coverage is broken. Just ran into it today. That should be a separate issue. I'm not sure what's causing that, I wasn't able to dig into it. I worked around it by grabbing a Gemfile.lock from another module I had on my laptop, so I'm guessing it's related to gem upgrades too.

**Comment by walkamongus** [comment]
#130 might be affecting you re: Rakefile

**Comment by richburroughs** [comment]
Looks like this was probably that other issue, which wasn't the skeleton's fault. Closing.

**Pull request closed without merging**
